[tool.poetry]
name = "positional-ngrams"
version = "0.1.0"
description = "Find the most common n-grams by position"
authors = ["Lucas Connors <lucas.revolutiontech@gmail.com>"]
license = "ISC"
readme = "README.md"
packages = [{include = "positional_ngrams"}]

[tool.poetry.dependencies]
python = "^3.8"
nltk = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
